// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqwebMW_3dS4RROf1shE5NcmXT6ZnQCbM',
    appId: '1:277597954919:web:8a7ed04cf8590129b0c5c2',
    messagingSenderId: '277597954919',
    projectId: 'sample-project-74cd8',
    authDomain: 'sample-project-74cd8.firebaseapp.com',
    databaseURL: 'https://sample-project-74cd8-default-rtdb.firebaseio.com',
    storageBucket: 'sample-project-74cd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgLQYicnhXIfIkub-pZSRj3jMO9NCUj8',
    appId: '1:277597954919:android:4bcaa09eed6d55beb0c5c2',
    messagingSenderId: '277597954919',
    projectId: 'sample-project-74cd8',
    databaseURL: 'https://sample-project-74cd8-default-rtdb.firebaseio.com',
    storageBucket: 'sample-project-74cd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5qRerL6wMX9I0dUsjrrEOYxHDylnpMR4',
    appId: '1:277597954919:ios:c4a9010592959f9cb0c5c2',
    messagingSenderId: '277597954919',
    projectId: 'sample-project-74cd8',
    databaseURL: 'https://sample-project-74cd8-default-rtdb.firebaseio.com',
    storageBucket: 'sample-project-74cd8.appspot.com',
    iosBundleId: 'com.example.firebaseSample',
  );
}
